### ISSUE TITLE
KVM driver build fail with latest kvmi crate

### ISSUE THREAD

**Issue by Wenzel** [Wenzel/libmicrovmi#116]
https://github.com/Wenzel/libmicrovmi/pull/115/checks?check_run_id=1000813980#step:10:87

The tests are failing if we use kvmi `master` branch (or the one I uploaded on crates.io)
 This should be a simple fix.

**Comment by rageagainsthepc** [comment]
Yes, the fix is to not use the crates.io version just yet. The kvmi master branch contains changes that are needed for @arnabcs17b006 pagefault PR.

**Comment by Wenzel** [comment]
Solved by merging https://github.com/Wenzel/libmicrovmi/pull/89
