### ISSUE TITLE
Physical write function should not require a mutable buffer

### ISSUE THREAD

**Issue by ko1N** [Wenzel/libmicrovmi#144]
When doing a physical write the input byte buffer that is being written to the target is usually not mutated directly. It will just cause the memory of the target to be mutated. Currently, the libmicrovmi API exposes a physical write function that enforces mutability of the input byte buffer though.

```rust
    fn write_physical(&self, _paddr: u64, _buf: &mut [u8]) -> Result<(), Box<dyn Error>> {
        unimplemented!();
    }
```

**Comment by Wenzel** [comment]
I already opened an issue after our discussion a few hours ago:
https://github.com/Wenzel/libmicrovmi/issues/141

:-)
