### ISSUE TITLE
Halt introspected VM on volatility execution

### ISSUE THREAD

**Issue by dommi22m** [Wenzel/libmicrovmi#246]
Hi @Wenzel !

I'm currently trying your volatility3-plugin. What i try is to halt the introspected VM on volatility execution.
Do you think this patch 058dc5ba25a50e3462c7e596994a153cb13f6105 is doing the job right?
("Inspired" by your [example](https://github.com/Wenzel/libmicrovmi/blob/master/python/examples/mem-dump.py))

Thank you in advance
Tommy

**Comment by Wenzel** [comment]
Hi @dommi22m 

It looks like this is the right patch to enforce pausing VM while taking the memory dump.
Did you tested that code already ?

**Comment by dommi22m** [comment]
Yes, seams to work correctly.
Thank's for your response!
