### ISSUE TITLE
Redesign the init function so it returns result objects

### ISSUE THREAD

**Issue by rageagainsthepc** [Wenzel/libmicrovmi#67]
When using libmicrovmi in an external project it is rather unfortunate to have the init function just panic if something goes wrong. Imho it would be better to have it return result objects instead so the caller can decide how to handle the situation.
One example is libvmi which tests hypervisor connections by initializing them. If one fails, libvmi just moves on to the next one.

**Comment by Wenzel** [comment]
Do you mean it panics if an API is unimplemented ?

Also, I used unwrap() a lot in the library where I shouldn't, because I'm not familiar with proper error handling in Rust at this point.

Feel free to improve it.

**Comment by rageagainsthepc** [comment]
> Also, I used unwrap() a lot in the library where I shouldn't, because I'm not familiar with proper error handling in Rust at this point.

That's exactly what I mean ;) Ok, will do.

**Comment by Wenzel** [comment]
closed by https://github.com/Wenzel/libmicrovmi/pull/151
